### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by joao-parana** [swashata/ipt-knowledgebase-theme-wp#4]
I'm new on Wordpress Development but I am interested in translating your theme to Brazilian Portuguese and pull the request here. Where can I see the instructions to do that. I'm particularly interested in the instructions related to the bbpress translation issues (inside your code).

**Comment by swashata** [comment]
Hello,

Please see this. https://make.wordpress.org/polyglots/handbook/tools/poedit/
