### ISSUE TITLE
Warning after upgrade to WP 3.9.2

### ISSUE THREAD

**Issue by mathetos** [swashata/ipt-knowledgebase-theme-wp#5]
After upgrading to WP 3.9.2 we got this warning on our site, even with debug turned off:

`Warning: join() [function.join]: Invalid arguments passed in /home/fooplugi/docs.fooplugins.com/wp-includes/post-template.php on line 478
class="">`

We went into [extras.php](https://github.com/swashata/ipt-knowledgebase-theme-wp/blob/master/inc/extras.php) and disabled line 30:

`// add_filter( 'body_class', 'ipt_kb_body_classes' );`

That resolved it. I'm not sure if we're missing any features of the theme because of that, but so far we're in good shape.

**Comment by swashata** [comment]
I guess this has been solved with WP 4.0, since I can not see any further error.
