### ISSUE TITLE
get_stylesheet_directory_uri() used in functions.php breaks child themes

### ISSUE THREAD

**Issue by akshayraje** [swashata/ipt-knowledgebase-theme-wp#6]
In the function ipt_kb_scripts() in functions.php, get_stylesheet_directory_uri() has been used at a couple of places. This should be replaced with get_template_directory_uri() so that it becomes more compatible with child themes.

Also, it would make sense to declaring functions in functions.php conditionally to make them pluggable as recommended in http://codex.wordpress.org/Child_Themes#Using_functions.php

**Comment by swashata** [comment]
Thanks
