### ISSUE TITLE
Google Webmaster Tools Structured Data Errors

### ISSUE THREAD

**Issue by offgridsoftware** [swashata/ipt-knowledgebase-theme-wp#7]
Getting structured data errors in webmaster tools.

![webmaster_tools_-_structured_data_2015-04-28_10 52 58](https://cloud.githubusercontent.com/assets/12157387/7377029/add87f2e-ed98-11e4-8c65-5ac586a8b4e1.png)

The theme isn't including author and updating info.

![webmaster_tools_-_structured_data_2015-04-28_11 22 49](https://cloud.githubusercontent.com/assets/12157387/7377962/d6366c0a-ed9e-11e4-8cec-494ef85a522d.png)
![webmaster_tools_-_structured_data_2015-04-28_11 24 29](https://cloud.githubusercontent.com/assets/12157387/7377963/db6e3df6-ed9e-11e4-81ef-21ff1483641e.png)

I found this website that detailed the exact problem I'm having and what they did to fix it in their theme. Disregard the title fix since I see in your theme this works fine. Only the author and updating give me errors.
https://www.acceleratormarketing.com/trench-report/google-analytics-errors-and-structured-data/

I tried to find where to make these changes in your theme but was unsuccessful.

**Comment by swashata** [comment]
This is not within the scope of this theme. I personally use Yoast SEO plugin for including all structured data.
